"""
Three-layer prompt-injection defence for DPDP Mitra.

Layer 1 (check_injection)  — detect injection phrases BEFORE calling the LLM.
Layer 2                    — hardened system prompt prefix (in prompts.py).
Layer 3 (check_output_scope) — heuristic scope check on the LLM reply AFTER
                               it returns, without a second LLM call.
"""

# ── Layer 1 — injection phrase blocklist ─────────────────────────────────────

_INJECTION_PHRASES: list[str] = [
    "ignore all rules",
    "ignore previous instructions",
    "ignore the above",
    "disregard all",
    "disregard previous",
    "forget your instructions",
    "you are now",
    "act as",
    "pretend you are",
    "new instructions",
    "system prompt",
    "override",
    "ignore your",
]

# Fixed refusal strings — never generated by the LLM.
REFUSAL_EN = (
    "I can't process that request. "
    "I'm only able to help with questions about the DPDP Act, 2023."
)
REFUSAL_HI = (
    "मैं इस अनुरोध को प्रोसेस नहीं कर सकता। "
    "मैं केवल DPDP अधिनियम, 2023 से संबंधित प्रश्नों में सहायता कर सकता हूं।"
)


def refusal_text(lang: str) -> str:
    return REFUSAL_HI if lang == "hi" else REFUSAL_EN


def check_injection(text: str, lang: str) -> str | None:
    """
    Return the appropriate refusal string if an injection phrase is found
    in *text* (case-insensitive substring match), otherwise return None.
    """
    lower = text.lower()
    for phrase in _INJECTION_PHRASES:
        if phrase in lower:
            print(
                f"[security] Injection attempt blocked — matched phrase: {phrase!r} "
                f"in message: {text[:120]!r}"
            )
            return refusal_text(lang)
    return None


# ── Layer 3 — output scope heuristic ─────────────────────────────────────────

# If the LLM reply contains ANY of these terms, it's almost certainly on-topic.
_DPDP_REPLY_KEYWORDS: list[str] = [
    "dpdp",
    "data principal",
    "data fiduciary",
    "section",
    "धारा",
    "अधिनियम",
    "personal data",
    "consent",
    "data protection",
    "data protection board",
    "act, 2023",
    "significant data fiduciary",
    "notice",
    "grievance",
]

# If the user message contains ANY of these, the question itself was DPDP-related;
# we trust the answer even if the reply keywords are absent.
_DPDP_QUERY_KEYWORDS: list[str] = [
    "dpdp",
    "data protection",
    "personal data",
    "data principal",
    "data fiduciary",
    "section",
    "consent",
    "privacy",
    "right",
    "obligation",
    "notice",
    "grievance",
    "act",
    "धारा",
    "अधिनियम",
    "डेटा",
    "सहमति",
    "गोपनीयता",
]


def _contains_any(text: str, keywords: list[str]) -> bool:
    lower = text.lower()
    return any(kw in lower for kw in keywords)


def check_output_scope(user_message: str, reply: str, lang: str) -> str | None:
    """
    Return the refusal string if BOTH the LLM reply AND the user's original
    message show no DPDP relevance — a strong signal the model drifted off-topic.
    Returns None (allow reply through) otherwise.
    """
    if _contains_any(reply, _DPDP_REPLY_KEYWORDS):
        return None  # reply looks on-topic
    if _contains_any(user_message, _DPDP_QUERY_KEYWORDS):
        return None  # user's question was DPDP-related — trust the answer
    print(
        "[security] Output scope check blocked reply — no DPDP terms in reply "
        f"or user message. User message: {user_message[:120]!r}"
    )
    return refusal_text(lang)
