"""
Four-layer prompt-injection / citation-grounding defence for DPDP Mitra.

Layer 1 (check_injection)        — detect injection phrases BEFORE calling the LLM.
Layer 2                          — hardened system prompt prefix (in prompts.py).
Layer 3 (check_output_scope)     — heuristic scope check on the LLM reply AFTER
                                   it returns, without a second LLM call.
Layer 4 (check_citation_grounding) — log-only: flag citations that do not match
                                   the headers actually present in the retrieved
                                   context block for this turn.
"""

import re
import logging

logger = logging.getLogger(__name__)

# ── Layer 1 — injection phrase blocklist ─────────────────────────────────────

_INJECTION_PHRASES: list[str] = [
    "ignore all rules",
    "ignore previous instructions",
    "ignore the above",
    "disregard all",
    "disregard previous",
    "forget your instructions",
    "you are now",
    "act as",
    "pretend you are",
    "new instructions",
    "system prompt",
    "override",
    "ignore your",
]

# Fixed refusal strings — never generated by the LLM.
REFUSAL_EN = (
    "I can't process that request. "
    "I'm only able to help with questions about the DPDP Act, 2023."
)
REFUSAL_HI = (
    "मैं इस अनुरोध को प्रोसेस नहीं कर सकता। "
    "मैं केवल DPDP अधिनियम, 2023 से संबंधित प्रश्नों में सहायता कर सकता हूं।"
)


def refusal_text(lang: str) -> str:
    return REFUSAL_HI if lang == "hi" else REFUSAL_EN


def check_injection(text: str, lang: str) -> str | None:
    """
    Return the appropriate refusal string if an injection phrase is found
    in *text* (case-insensitive substring match), otherwise return None.
    """
    lower = text.lower()
    for phrase in _INJECTION_PHRASES:
        if phrase in lower:
            print(
                f"[security] Injection attempt blocked — matched phrase: {phrase!r} "
                f"in message: {text[:120]!r}"
            )
            return refusal_text(lang)
    return None


# ── Layer 3 — output scope heuristic ─────────────────────────────────────────

# If the LLM reply contains ANY of these terms, it's almost certainly on-topic.
_DPDP_REPLY_KEYWORDS: list[str] = [
    "dpdp",
    "data principal",
    "data fiduciary",
    "section",
    "धारा",
    "अधिनियम",
    "personal data",
    "consent",
    "data protection",
    "data protection board",
    "act, 2023",
    "significant data fiduciary",
    "notice",
    "grievance",
]

# If the user message contains ANY of these, the question itself was DPDP-related;
# we trust the answer even if the reply keywords are absent.
_DPDP_QUERY_KEYWORDS: list[str] = [
    "dpdp",
    "data protection",
    "personal data",
    "data principal",
    "data fiduciary",
    "section",
    "consent",
    "privacy",
    "right",
    "obligation",
    "notice",
    "grievance",
    "act",
    "धारा",
    "अधिनियम",
    "डेटा",
    "सहमति",
    "गोपनीयता",
]


def _contains_any(text: str, keywords: list[str]) -> bool:
    lower = text.lower()
    return any(kw in lower for kw in keywords)


def check_output_scope(user_message: str, reply: str, lang: str) -> str | None:
    """
    Return the refusal string if BOTH the LLM reply AND the user's original
    message show no DPDP relevance — a strong signal the model drifted off-topic.
    Returns None (allow reply through) otherwise.
    """
    if _contains_any(reply, _DPDP_REPLY_KEYWORDS):
        return None  # reply looks on-topic
    if _contains_any(user_message, _DPDP_QUERY_KEYWORDS):
        return None  # user's question was DPDP-related — trust the answer
    print(
        "[security] Output scope check blocked reply — no DPDP terms in reply "
        f"or user message. User message: {user_message[:120]!r}"
    )
    return refusal_text(lang)


# ── Layer 4 — citation grounding check (log-only, not a hard block) ───────────

# Matches "Party Name v. Other Party" or "Party Name vs Other Party" patterns.
# Capturing groups are intentionally broad — we strip and normalise afterwards.
_CASE_CITE_RE = re.compile(
    r"([A-Z][A-Za-z\.&\s\(\)\']{1,60}?)\s+v(?:s\.?)?\.?\s+([A-Z][A-Za-z\.&\s\(\)\']{1,60}?)(?=[,\.\;\(\"\n]|$)",
)

# Matches "Section 8(5)" / "Section 17(2)(a)" in English replies.
_SECTION_EN_RE = re.compile(r"\bSection\s+([\d][\w\(\)]*)", re.IGNORECASE)
# Matches "धारा 8(5)" in Hindi replies.
_SECTION_HI_RE = re.compile(r"धारा\s+([\d][\w\(\)]*)")

# ── Out-of-scope vendor/firm recommendation detection (log-only) ──────────────
# A small starter denylist of consulting/advisory firm names. Vendor names are
# never present in the corpus, so any of these appearing in a reply is suspect.
_FIRM_DENYLIST: list[str] = [
    "deloitte", "kpmg", "pwc", "pricewaterhousecoopers", "ernst & young",
    "ernst and young", "grant thornton", "accenture", "mckinsey", "bcg",
    "boston consulting", "bain", "infosys", "tcs", "wipro", "cognizant",
    "tata consultancy",
]
# "EY" as a standalone token (word-boundary, case-sensitive uppercase) — avoids
# matching "they", "key", "money" etc. that a substring search would catch.
_EY_RE = re.compile(r"\bEY\b")

# "firms such as X, Y, Z" / "companies like X, Y and Z" enumeration patterns.
_FIRM_ENUM_RE = re.compile(
    r"\b(?:firms|companies|consultancies|vendors|providers|auditors)\s+"
    r"(?:such as|like|including|e\.g\.?)\s+([A-Z][A-Za-z0-9&\.\,\s]{3,120})",
    re.IGNORECASE,
)


def _names_overlap(cited: str, title: str) -> bool:
    """Return True when cited case name and retrieved doc_title likely refer to the same case."""
    if cited in title or title in cited:
        return True
    # Word-level overlap: require ≥2 significant words in common (handles "K.S. Puttaswamy v. Union
    # of India" matching "Justice K.S. Puttaswamy (Retd.) v. Union of India").
    stops = {"v.", "v", "vs", "vs.", "state", "of", "the", "union", "india", "&",
             "anr.", "ors.", "retd.", "justice", "mr.", "mrs.", "dr.", "in", "and"}
    cited_sig = {w for w in cited.split() if w not in stops and len(w) > 1}
    title_sig = {w for w in title.split() if w not in stops and len(w) > 1}
    return len(cited_sig & title_sig) >= 2


def check_citation_grounding(
    reply: str,
    all_chunks: list[dict],
    user_message: str,
) -> None:
    """
    Layer 4 — log-only citation grounding check.

    Warns (logger.warning) when the LLM response cites a case name or DPDP Act
    section that was NOT present as a header in the retrieved context block for
    this turn.  This is a monitoring signal — it does NOT block or modify the reply.
    Call this ONLY when the reply has already passed the Layer 3 scope check.
    """
    from retrieval import CASE_LAW_RELEVANCE_THRESHOLD  # local import avoids circular at module load

    act_chunks = [c for c in all_chunks if c.get("doc_type") != "case_law"]
    case_law_chunks = [
        c for c in all_chunks
        if c.get("doc_type") == "case_law"
        and c.get("similarity_score", 1.0) < CASE_LAW_RELEVANCE_THRESHOLD
    ]

    # ── Case-name check ───────────────────────────────────────────────────────
    cited_cases = [
        f"{m.group(1).strip().lower()} v. {m.group(2).strip().lower()}"
        for m in _CASE_CITE_RE.finditer(reply)
        if len(m.group(1).strip()) > 2 and len(m.group(2).strip()) > 2
    ]

    if cited_cases:
        if not case_law_chunks:
            logger.warning(
                "[citation-grounding] Reply cites case(s) but no case-law was retrieved "
                "this turn. Cited: %r | query: %.120s",
                cited_cases[:5],
                user_message,
            )
        else:
            retrieved_titles = [
                (c.get("doc_title") or "").lower()
                for c in case_law_chunks
            ]
            for cited in cited_cases:
                if not any(_names_overlap(cited, t) for t in retrieved_titles if t):
                    logger.warning(
                        "[citation-grounding] Cited case not in retrieved context: %r | "
                        "retrieved titles: %r | query: %.120s",
                        cited,
                        retrieved_titles,
                        user_message,
                    )

    # ── DPDP Act section check ────────────────────────────────────────────────
    if act_chunks:
        cited_sections: set[str] = set()
        for m in _SECTION_EN_RE.finditer(reply):
            cited_sections.add(m.group(1).lower())
        for m in _SECTION_HI_RE.finditer(reply):
            cited_sections.add(m.group(1).lower())

        retrieved_section_nums: set[str] = set()
        for c in act_chunks:
            raw = (c.get("section") or "").lower()
            # Normalise "section 8(5)" → "8(5)", or pass through if already bare
            m = re.match(r"section\s+(.*)", raw)
            retrieved_section_nums.add(m.group(1).strip() if m else raw.strip())

        for sec in cited_sections:
            if sec not in retrieved_section_nums:
                logger.warning(
                    "[citation-grounding] DPDP section cited not in retrieved context: "
                    "Section %s | retrieved: %r | query: %.120s",
                    sec,
                    sorted(retrieved_section_nums),
                    user_message,
                )

    # ── Out-of-scope vendor/firm recommendation check (separate log category) ──
    _check_out_of_scope_recommendation(reply, user_message)


def _check_out_of_scope_recommendation(reply: str, user_message: str) -> None:
    """
    Log-only detection of vendor/consulting-firm recommendations leaking into a
    reply. Vendor names are never present in the RAG corpus, so any named firm is
    out of scope. Logged under the distinct `out_of_scope_recommendation` category
    so its frequency can be assessed independently of `citation-grounding` warnings.
    Never blocks or modifies the reply.
    """
    lower = reply.lower()

    hits = [name for name in _FIRM_DENYLIST if name in lower]
    if _EY_RE.search(reply):
        hits.append("EY")

    enum_match = _FIRM_ENUM_RE.search(reply)

    if hits or enum_match:
        logger.warning(
            "[out_of_scope_recommendation] Reply appears to name/recommend "
            "firms or vendors. Denylist hits: %r | enumeration: %r | query: %.120s",
            hits,
            enum_match.group(0)[:120] if enum_match else None,
            user_message,
        )
